# -*- coding: utf-8 -*-
"""timeseries_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DcMeSdGEE_4ZvNzjquugrpPMVmcrh9-4
"""

# STEP 1: Upload the Excel file
from google.colab import files
uploaded = files.upload()

import pandas as pd

file_name = list(uploaded.keys())[0]  # get the uploaded file name
df = pd.read_excel(file_name, sheet_name='Sheet1')











# STEP 3: Convert 'Month' to datetime and set it as index
df['Month'] = pd.to_datetime(df['Month'])
df.set_index('Month', inplace=True)

# STEP 4: Plot the time series
import matplotlib.pyplot as plt

plt.figure(figsize=(14, 6))
plt.plot(df['Total_Power_Purchase'], marker='o', color='blue')
plt.title('Total Power Purchase Over Time')
plt.xlabel('Month')
plt.ylabel('Total Power Purchase')
plt.grid(True)
plt.tight_layout()
plt.show()

# STEP 5: Correlation heatmap
import seaborn as sns

sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# STEP 1: Define train-test split
n_test = 12  # last 12 months for testing
train = df['Total_Power_Purchase'][:-n_test]
test = df['Total_Power_Purchase'][-n_test:]

# STEP 1: Install required library (if not already installed)
!pip install statsmodels --quiet

# STEP 2: Fit SARIMA on the training data
from statsmodels.tsa.statespace.sarimax import SARIMAX

model = SARIMAX(train,
                order=(1,1,1),
                seasonal_order=(1,1,1,12),
                enforce_stationarity=False,
                enforce_invertibility=False)

results = model.fit(disp=False)
print(results.summary())

# Run ADF test on original series
adf_test(df['Total_Power_Purchase'], 'Original Series')

# STEP 1: Import SARIMAX model
from statsmodels.tsa.statespace.sarimax import SARIMAX

# STEP 2: Drop NA values caused by differencing
ts_data = df['Total_Power_Purchase'].dropna()

# STEP 3: Fit SARIMA model (p,d,q)(P,D,Q,s)
# We'll use (1,1,1)(1,1,1,12) as a starting point
# You can tune it later using AIC/BIC or auto_arima
df = df.asfreq('MS')
model = SARIMAX(ts_data,
                order=(1,1,1),         # (p,d,q)
                seasonal_order=(1,1,1,12),  # (P,D,Q,s)
                enforce_stationarity=False,
                enforce_invertibility=False)

results = model.fit(disp=False)
print(results.summary())

# Diagnostic plots
results.plot_diagnostics(figsize=(16, 8))
plt.show()

import pickle

with open("sarima_model.pkl", "wb") as f:
    pickle.dump(results, f)